name: windmill scripts
run-name: ${{ github.actor }} running tests
on: [push]
jobs:
  unit-test:
    runs-on: ubuntu-latest
    container: ghcr.io/astral-sh/uv:debian
    steps:
      - uses: actions/checkout@v5
      - run: |
          echo "### Unit Test Coverage Report" >> $GITHUB_STEP_SUMMARY
          echo '```text' >> $GITHUB_STEP_SUMMARY
          PYTHONPATH=. uv run pytest pvr_flow/tests/unit/ --cov=pvr_flow --cov-report=term-missing >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
  property-test:
    runs-on: ubuntu-latest
    container: ghcr.io/astral-sh/uv:debian
    steps:
      - uses: actions/checkout@v5
      - run: PYTHONPATH=. uv run pytest pvr_flow/tests/property/